<?php

/**
 * @file
 * Contains ngt.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormState;
use Drupal\Core\Form\FormStateInterface;
use Drupal\file\Entity\File;

/**
 * Implements hook_help().
 */
function ngt_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the ngt module.
        case 'help.page.ngt':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('ngt') . '</p>';
        return $output;

    default:
    }
}

/**
 * Prepares variables for the html.html.twig template.
 */
function ngt_preprocess_html(&$variables) {

  // build uri logo
  $image_src = '';
  $conf = \Drupal::config('ngt.adminSettingsGeneral');
  $img = $conf->get('img_logo');
  if ( is_array($img) ) {
    $fid = reset($img);  
    $file = File::load($fid);
    isset($file) ? $image_src = $file->getFileUri() : '';
  }

  // global variables
  $variables['general_logo'] = $image_src;
  $variables['general_txt_curso'] = \Drupal::config('ngt.adminSettingsGeneral')->get('txt_curso');
  $variables['general_txt_newsletter'] = \Drupal::config('ngt.adminSettingsGeneral')->get('txt_newsletter');
  $variables['general_txt_footer'] = \Drupal::config('ngt.adminSettingsGeneral')->get('txt_footer');
}

/**
 * Implements hook_theme().
 */
function ngt_theme() {
  return [
    'course_main' => [
      'variables' => [
        'course' => NULL,
        'txt_curso' => NULL,
      ],
      'template' => 'block--course-main',
    ],
    'course_category' => [
      'variables' => [
        'category' => NULL,
      ],
      'template' => 'block--course-category',
    ],
    'course_content_dest' => [
      'variables' => [
        'contents' => NULL,
      ],
      'template' => 'block--contenido-destacado',
    ],
    'benefit_home' => [
      'variables' => [
        'benefit_1' => NULL,
        'benefit_2' => NULL,
        'benefit_3' => NULL,
      ],
      'template' => 'block--benefit-home',
    ],
  ];
}

// $tree = \Drupal::entityTypeManager()
//       ->getStorage('taxonomy_term')
//       ->loadTree(
//         'some_vocabulary', // This is your taxonomy term vocabulary (machine name).
//         0,                 // This is "tid" of parent. Set "0" to get all.
//         1,                 // Get only 1st level.
//         TRUE               // Get full load of taxonomy term entity.
//       );