<?php

/**
 * @file
 * Contains ngt_general.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormState;
use Drupal\Core\Form\FormStateInterface;
use Drupal\file\Entity\File;

/**
 * Implements hook_help().
 */
function ngt_general_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the ngt module.
        case 'help.page.ngt_general':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('ngt general') . '</p>';
        return $output;

    default:
    }
}


/**
 * Implements hook_preprocess().
 * 
 * Prepares variables for the html.html.twig template.
 * Inlcuye la directiva de angular la etiqueta html
 * 
 */
function ngt_general_preprocess_html(&$variables){
  $variables['html_attributes']['data.ng-app'] = 'ngtApp';
  // global variables
  $config = \Drupal::config('ngt_general.settings');  
  
  $logo_general_fid = reset($config->get('general_settings')['img_logo']);
  $logo_general_file = File::load($logo_general_fid);
  $logo_general_url = isset($logo_general_file) ? $logo_general_file->getFileUri() : '';

  $logo_second_fid = reset($config->get('general_settings')['img_logo_second']);
  $logo_second_file = File::load($logo_second_fid);
  $logo_second_url = isset($logo_second_file) ? $logo_second_file->getFileUri() : '';

  $logo_design_fid = reset($config->get('general_settings')['img_logo_design_by']);
  $logo_design_file = File::load($logo_design_fid);
  $logo_design_url = isset($logo_design_file) ? $logo_design_file->getFileUri() : '';

  $activate_img_logo_second = $config->get('general_settings')['activate_img_logo_second'];

  $variables['logo_general_url'] = $logo_general_url;
  $variables['logo_second_url'] = $logo_second_url;
  $variables['logo_design_url'] = $logo_design_url;
  $variables['activate_img_logo_second'] = $activate_img_logo_second;
}

/**
 * Implements hook_theme().
 */
function ngt_general_theme() {
  return [
    'course_main' => [
      'variables' => [
        'course' => NULL,
        'txt_curso' => NULL,
      ],
      'template' => 'block--course-main',
    ],
    'course_category' => [
      'variables' => [
        'main_category' => NULL,
      ],
      'template' => 'block--course-category',
    ],
    'course_content_dest' => [
      'variables' => [
        'contents' => NULL,
      ],
      'template' => 'block--contenido-destacado',
    ],
    'benefit_home' => [
      'variables' => [
        'benefit_1' => NULL,
        'benefit_2' => NULL,
        'benefit_3' => NULL,
      ],
      'template' => 'block--benefit-home',
    ],
    'node_top_course' => [
      'variables' => [
        'data' => NULL,
      ],
      'template' => 'node-course/block--top-course',
    ],
    'node_left_course' => [
      'variables' => [
        'data' => NULL,
      ],
      'template' => 'node-course/block--left-course',
    ],
    'node_right_course' => [
      'variables' => [
        'data' => NULL,
      ],
      'template' => 'node-course/block--right-course',
    ],
    'node_more_course' => [
      'variables' => [
        'data' => NULL,
      ],
      'template' => 'node-course/block--more-course',
    ],
  ];
}

